<a href="https://colab.research.google.com/github/Ritik-jangra/ShadowFox/blob/main/Store_Sales_Analyses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Store Sales and Profit Analysis Task

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Dataset/ShadowFox_Sales.csv")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [3]:
df.shape

(9800, 18)

In [4]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [6]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [14]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [15]:
df = df.dropna(subset=['Postal Code'])

In [16]:
df.isnull().sum().sum()

np.int64(0)

In [18]:
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

In [20]:
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst=True)

In [21]:
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['Day'] = df['Order Date'].dt.day

In [22]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Year,Month,Day
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2017,11,8
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017,11,8
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017,6,12
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016,10,11
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2016,10,11

In [23]:
# monthly sales
monthly_sales = df.groupby(['Year', 'Month'])['Sales'].sum().reset_index()

In [24]:
# create date column for plotting
monthly_sales['Date'] = pd.to_datetime(monthly_sales[['Year', 'Month']].assign(DAY=1))

monthly_sales.head()

   Year  Month      Sales       Date
0  2015      1  14205.707 2015-01-01
1  2015      2   4519.892 2015-02-01
2  2015      3  55205.797 2015-03-01
3  2015      4  27906.855 2015-04-01
4  2015      5  23644.303 2015-05-01

In [25]:
import plotly.express as px

fig = px.line(monthly_sales, x='Date', y='Sales', title='Monthly Sales Trend')
fig.show()

In [26]:
# category-wise sales
category_sales = df.groupby('Category')['Sales'].sum().reset_index()

category_sales

          Category        Sales
0        Furniture  723538.4757
1  Office Supplies  703212.8240
2       Technology  825856.1130

In [27]:
import plotly.express as px

fig = px.bar(category_sales, x='Category', y='Sales', title='Sales by Category')
fig.show()

In [29]:
# sub-category wise sales
subcat_sales = df.groupby('Sub-Category')['Sales'].sum().reset_index()

# sort descending
subcat_sales = subcat_sales.sort_values(by='Sales', ascending=False)

subcat_sales.head()

   Sub-Category       Sales
13       Phones  326487.698
5        Chairs  322107.531
14      Storage  217779.102
16       Tables  202810.628
3       Binders  200028.785

In [30]:
fig = px.bar(subcat_sales, x='Sub-Category', y='Sales',
             title='Sales by Sub-Category')

fig.show()

In [31]:
# profit column check
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Year', 'Month', 'Day'],
      dtype='object')

In [34]:
# segment-wise sales
segment_sales = df.groupby('Segment')['Sales'].sum().reset_index()

segment_sales

       Segment         Sales
0     Consumer  1.146708e+06
1    Corporate  6.822118e+05
2  Home Office  4.236874e+05

In [35]:
fig = px.pie(segment_sales, names='Segment', values='Sales',
             title='Sales by Customer Segment')
fig.show()

In [37]:
region_sales = df.groupby('Region')['Sales'].sum().reset_index()

fig = px.bar(region_sales, x='Region', y='Sales',
             title='Sales by Region')
fig.show()

In [38]:
top_customers = df.groupby('Customer Name')['Sales'].sum().reset_index()

top_customers = top_customers.sort_values(by='Sales', ascending=False).head(10)

top_customers

          Customer Name      Sales
686         Sean Miller  25043.050
730        Tamara Chand  19052.218
622        Raymond Buch  15117.339
757        Tom Ashbrook  14595.620
6         Adrian Barton  14473.571
441        Ken Lonsdale  14175.229
671        Sanjit Chand  14142.334
334        Hunter Lopez  12873.298
672        Sanjit Engle  12209.438
156  Christopher Conant  12129.072

In [39]:
# average sales per order
order_sales = df.groupby('Order ID')['Sales'].sum().reset_index()

order_sales['Avg Sales'] = order_sales['Sales']

order_sales.head()

         Order ID    Sales  Avg Sales
0  CA-2015-100006  377.970    377.970
1  CA-2015-100090  699.192    699.192
2  CA-2015-100293   91.056     91.056
3  CA-2015-100328    3.928      3.928
4  CA-2015-100363   21.376     21.376